name:                matrix-accelerate
version:             0.1.0.0
github:              "githubuser/matrix-accelerate"
license:             BSD-3-Clause
author:              "Noah Martin Williams"
maintainer:          "noahmartinwilliams@gmail.com"
copyright:           "2024 Noah Williams"
category:            Accelerate, Matrices, GPU
synopsis:            An accelerate library that adds dependently typed matrices.

extra-doc-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         An accelerate library that adds dependently typed matrices. 
  This library adds the ability to matrix manipulations with or without dependent types to help line up the operations 
  so as to prevent runtime errors.

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules: Data.Array.Accelerate.Matrix
  dependencies:
  - accelerate >= 1.3 && < 1.4
  - lens-accelerate >= 0.3 && < 0.4

tests:
  accelerate-matrix-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
